name: CI (Quality Check)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual runs

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  analyze:
    name: Flutter Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Create Dummy .env
        run: touch .env # Required because .env is listed as an asset in pubspec.yaml

      - name: Run Analysis
        run: flutter analyze
